### ISSUE TITLE
Precompiled SDK 1.37.22 doesn't exist for Windows

### ISSUE THREAD

**Issue by saschanaz** [juj/emsdk#110]
`emsdk list` doesn't report 1.37.22 on Windows.

This exists: https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_64bit/emscripten-llvm-e1.37.21.zip

This doesn't: https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_64bit/emscripten-llvm-e1.37.22.zip

**Comment by RyanAveryBSU** [comment]
Unpacking 'C:/Users/Ryan/Desktop/emsc/zips/emscripten-llvm-e1.37.21.zip' to 'C:/Users/Ryan/Desktop/emsc/clang/e1.37.21_64bit'
Unzipping file 'C:/Users/Ryan/Desktop/emsc/zips/emscripten-llvm-e1.37.21.zip' failed due to reason: File is not a zip file! Removing the corrupted zip file.
Installation failed!

this what I get tonight. idk how I ended up on this page fwiw

**Comment by saschanaz** [comment]
Also see https://github.com/kripken/emscripten/issues/5713, @juj is working on this.

**Comment by saschanaz** [comment]
Fixed now :tada:
