### ISSUE TITLE
avoid generating WebIDLGrammar.pkl and parser.out files (or generate in build directory)

### ISSUE THREAD

**Issue by timotheecour** [juj/emsdk#151]
running tools/webidl_binder.py generates WebIDLGrammar.pkl and parser.out files (which cause users to add these to their .gitignore etc); 
would like to:
* allow skipping generating these
* or at least customizing the dir where these go

**Comment by kripken** [comment]
Probably best to file this on the main emscripten repo, as the fix is probably going to be in `tools/webidl_binder.py` which is in there.

I think the `pkl` and other file are generated by `third_party/WebIDL.py` which the WebIDL binder uses. We can maybe just modify that file to not emit those files, although I assume it's an optimization of some sort, not sure how important.
