### ISSUE TITLE
1.38.7 build error "cannot find binaryen js libraries"

### ISSUE THREAD

**Issue by TrevorSundberg** [juj/emsdk#157]
Using the latest pre-built library on emsdk (1.38.7) I get the error:
```
CRITICAL:root:emcc: cannot find binaryen js libraries (tried: ('C:/Users/Trevor/Desktop/Emsdk/clang/e1.38.7_64bit/binaryen\\bin', 'C:/Users/Trevor/Desktop/Emsdk/clang/e1.38.7_64bit/binaryen\\share\\binaryen'))
```
I checked the latest repository and saw that you changed `shared.py` to look for `wasm.js`, so I did the same and it worked. Feels like that change should be in 1.38.7 since `binaryen.js` was removed.

Not sure if this bug should be filed here or on emscripten.

**Comment by TrevorSundberg** [comment]
Just looked and saw 1.38.8 on emscripten's Releases, and I'm guessing that has the fix.

**Comment by kripken** [comment]
Yeah, exactly - we only noticed the breakage after tagging the build, sorry about that. 1.38.8 is confirmed as working, binary builds are on the way.

**Comment by theparitt** [comment]
I have the same problem for emscriten 1.38.29 in Windows 10 64-bit

cannot find binaryen js libraries

please help

**Comment by theparitt** [comment]
since noone replied and seems this post is dead.
I fixed everythin by myself as usual.

I am not sure that the problem that I have two versions of emsdk.
so I activate 
emsdk activate latest --global
emsdk_env

then delete everything in build/ folder ( i use CMake and target of CMake is build/ )
run everything again

emconfigure cmake .  -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=1
emconfigure make 

then everything is fine
