### ISSUE TITLE
Cannot activate both clang-e1.38.11-64bit and emscripten-incoming-64bit

### ISSUE THREAD

**Issue by eclecticdave** [juj/emsdk#169]
Hi,

Having recently done 'emsdk update', I found I was unable to activate both clang-e1.38.11-64bit and emscripten-incoming-64bit at the same time. Attempting to activate emscripten deactivates clang and if I then try to reactivate clang it deactivates emscripten!

With the help of EMSDK_VERBOSE I've tracked the issue down to the fact that both tools have defined EMSCRIPTEN_NATIVE_OPTIMIZER in emsdk_manifest.json with different values.  This leads to the error message "**_tool_ is not active, because key=EMSCRIPTEN_NATIVE_OPTIMIZER has value _xxxx_ but should have value _yyyy_**" being printed causing the tool to be deactivated.

If I modify emsdk_manifest.json and remove the EMSCRIPTEN_NATIVE_OPTIMIZER setting from 'emscripten-incoming-64bit' it then allows both tools to be activated.

Which begs the question - which definition of EMSCRIPTEN_NATIVE_OPTIMIZER is the "correct" one -  does it matter whether I use the emscripten supplied optimizer or clang's?

**Comment by juj** [comment]
This kind of mixing of use of precompiled tags with use of non-precompiled branches has not been intended before. The issue here is that both optimizers are correct. With precompiled Clangs, Emscripten native optimizer is bundled into the Clang binary so that there is only one precompiled package to distribute. With the Emscripten branches, one needs to build the optimizer from source. With this kind of mixed use, there is no correct optimizer in the sense that they both do come with the optimizer; perhaps either of them might be desired to be used.

I'd recommend here to either manually modify emsdk_manifest like you did to use one specifically, or to pair clang-e1.38.11-64bit with emscripten-1.38.11-64bit, or use the incoming branch altogether.

**Comment by eclecticdave** [comment]
OK, I see.  I need to use emscripten_incoming in order the contribute PRs.  The problem I have with using the clang_incoming package is my rather old and modest laptop struggles to compile it, so I find it easier to use a binary package.

No problem, I can live with modifying the manifest file.  Good to know the optimizers are essentially the same so it shouldn't matter which one I pick.
