### ISSUE TITLE
Proposal to use `click` for emsdk python file

### ISSUE THREAD

**Issue by koutoftimer** [juj/emsdk#178]
I found big and ugly logic in [emsdk][1] for processing command line arguments. Will it be better to use [click][2] for this? It offers [great docs][3].

   [1]: https://github.com/juj/emsdk/blob/master/emsdk
   [2]: https://github.com/pallets/click
   [3]: https://click.palletsprojects.com/en/7.x/

**Comment by juj** [comment]
The code for processing command line arguments may not be the simplest, but the code is very stable and there are only infrequent modifications to it, which is why it is probably no use to go and turn it upside down to rewrite it. In any case, if someone does want to rewrite it, it needs to be done against something that does not require installing components from pip, but emsdk only uses core functionality offered by python without pip installable parts. That makes it easy to embed to other engine SDKs, while keeping the installable parts to a minimum.
