### ISSUE TITLE
std::vector of std::unique_ptr<>

### ISSUE THREAD

**Issue by Chiv76** [juj/emsdk#191]
I can not figure out how can I push instance of std::unique_ptr<> into approptiate vector. The minimal code is:
```c++
 #include <vector>
 #include <memory>
 #include <iostream>

 int main()
 {
   std::vector<std::unique_ptr<int> > int_v;
   // catch compile error next line:
   int_v.push_back(std::unique_ptr<int>(new int(123)));

   std::cout << *(int_v.back()) << std::endl;
 }
```
Same code works fine in different c++ compilers (msvs'17)

**Comment by phraemer** [comment]
Interesting. Looks like something is up with the move constructor
https://mbebenita.github.io/WasmExplorer/?state=%7B%22options%22%3A%7B%22showGutter%22%3Atrue%2C%22showConsole%22%3Atrue%2C%22showOptions%22%3Atrue%2C%22autoCompile%22%3Atrue%2C%22showLLVM%22%3Afalse%2C%22darkMode%22%3Atrue%2C%22fastMath%22%3Afalse%2C%22noInline%22%3Afalse%2C%22noRTTI%22%3Afalse%2C%22noExceptions%22%3Afalse%2C%22cleanWast%22%3Afalse%2C%22wasmBaseline%22%3Afalse%2C%22dialect%22%3A%22C%2B%2B1z%22%2C%22optimizationLevel%22%3A%22s%22%7D%2C%22source%22%3A%22%23include%20%3Cvector%3E%5Cn%23include%20%3Cmemory%3E%5Cn%5Cnint%20main()%5Cn%7B%5Cn%20std%3A%3Avector%3Cstd%3A%3Aunique_ptr%3Cint%3E%20%3E%20int_v%3B%5Cn%20%2F%2F%20catch%20compile%20error%20next%20line%3A%5Cn%20int_v.push_back(std%3A%3Amake_unique%3Cint%3E(123))%3B%5Cn%20auto%20x%20%3D%20int_v.back()%3B%5Cn%7D%22%7D

**Comment by Chiv76** [comment]
in addition - if it is possible to use c++11 (that's not my case, unfortunately), using emplace_back instead of push_back solves the problem. But, I've faced this issue cause I can't use c++11, which have no emplace_back method for vector

**Comment by juj** [comment]
This repository about the Emscripten SDK installer script, but not about the Emscripten compiler toolchain itself. Try reporting this at https://github.com/kripken/emscripten/issues.

It may be that the issue is something in Clang/LLVM version used by Emscripten, and newer version of LLVM would have a fix to that, so trying a native build against upstream LLVM/Clang and noting down the version might be a good test to check out. If so, then when Emscripten updates its LLVM version the next time, it would pick up a fix.

**Comment by Chiv76** [comment]
Ok, to be continued at https://github.com/kripken/emscripten/issues/7646
