### ISSUE TITLE
Please update released SDK - Missing fix for compiling Linux x64 after update

### ISSUE THREAD

**Issue by asRIA** [juj/emsdk#45]
Hi @juj, Fix for Linux x64 works fine, but looks that each `emsdk update` reverts state from before patch. It pulls already released old version.
Will it be possible to update released version of emsdk ?

Cheers,
Piotr

**Comment by juj** [comment]
Emsdk is updated with the same cadence as the Emscripten compiler versions are published. If you want to follow the latest github version, you can use

    git clone https://github.com/juj/emsdk.git

to install emsdk (instead of downloading a portable sdk), and use

    git pull

instead of `./emsdk update` to update to the latest in-development version.

Alternatively if you can bear to wait for a moment, the next release is coming soon, we are now preparing the next merge to master.

**Comment by asRIA** [comment]
OK, this should work as well. Thank you!
